name: Cron Consumer

on:
  schedule:
    - cron: "2/2 * * * *"

jobs:
  consume_artifact:
    name: "Consum Artifact"
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: cron-producer.yml
          name: run_number.txt

      - name: Print Artifact
        run: cat run_number.txt
