name: Cross-Job Outputs

on:
  pull_request:
    branches: [main]

# Cancel in-progress workflows from the same pull-request branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  generate_output:
    name: "Generate Output"
    runs-on: ubuntu-latest
    steps:
      - name: Set Output
        run: |
          echo "A=1" >> "$GITHUB_OUTPUT"
          echo "B=2" >> "$GITHUB_OUTPUT"

  read_output:
    name: "Read Output"
    needs: [ generate_output ]
    runs-on: ubuntu-latest
    steps:
      - name: Read Output
        run: |
          echo "A=${{ needs.generate_output.outputs.A }}"
          echo "B=${{ needs.generate_output.outputs.B }}"
