name: Workflow Dispatch Test

on:
  workflow_dispatch:
    inputs:
      message:
        description: "The message to print to `stdout`."
        required: true
        type: string
        default: "Hello, World!"


# Cancel any in-progress workflows.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Greeting"
        echo: |
          echo "${{ inputs.message }}"
