name: Environment Exploration

on:
  pull_request:
    branches: [main]

# Cancel in-progress workflows from the same pull-request branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  development:
    name: "Development"
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: "Checkout Sources"
        uses: actions/checkout@v3
      - run: |
          bash ./environment-specific.sh \
            ${{ secrets.ENVIRONMENT_SECRET }} \
            ${{ vars.ENVIRONMENT_NAME }}

  integration:
    name: "Integration"
    runs-on: ubuntu-latest
    environment: Integration
    steps:
      - name: "Checkout Sources"
        uses: actions/checkout@v3
      - run: |
          bash ./environment-specific.sh \
            ${{ secrets.ENVIRONMENT_SECRET }} \
            ${{ vars.ENVIRONMENT_NAME }}
