name: Fail if there are changes to noreview/

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "noreview/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # Adding a comment to bypass the noreview/** filter. Adding a change under
  # .github/ makes this workflow run.
  check-and-fail:
    name: "Check and fail"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Sources"
        uses: actions/checkout@v3
      - name: "Check and fail"
        run: |
          grep -r 'test' noreview/ && exit 1 || exit 0
