name: Label-dependent Workflow

on:
  pull_request:
    types: [labeled, opened, synchronize]
    branches: [main]

# Only consume labels from PRs one-at-a-time.
concurrency:
  group: ${{ github.workflow }}

jobs:
  consume_label:
    name: "Consume Label"
    if: contains(github.event.pull_request.labels.*.name, 'trigger-dependent-workflow')
    runs-on: ubuntu-latest
    steps:
      - name: "Declare Success"
        run: echo "It Worked!"
      - name: Actions Ecosystem Remove Labels
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          github_token: ${{ github.token }}
          labels: trigger-dependent-workflow
